# Generated by Django 4.2.5 on 2024-06-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('food_name', models.CharField(max_length=50)),
                ('prize', models.IntegerField()),
                ('image', models.ImageField(upload_to='food_images/')),
                ('food_type', models.CharField(choices=[('Non-Veg', 'Non-Veg'), ('Veg', 'Veg')], max_length=30)),
            ],
        ),
    ]
