# Generated by Django 4.2.5 on 2024-06-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.TextField(default='2020-12-13'),
            preserve_default=False,
        ),
    ]
