# Generated by Django 4.2.5 on 2024-06-16 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pizza_app', '0004_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.IntegerField()),
                ('all_items_ordered', models.BinaryField()),
                ('delivery_category', models.CharField(choices=[('Express-Delivery', 'Express-Delivery'), ('Standard-Delivery', 'Standard-Delivery')], default='Standard-Delivery', max_length=50)),
                ('delivery_charge', models.IntegerField(default=10)),
                ('total_price', models.IntegerField()),
                ('order_status', models.CharField(choices=[('PENDING', 'PENDING'), ('OUT-FOR-DELIVERY', 'OUT-FOR-DELIVERY'), ('DELIVERED', 'DELIVERED')], default='PENDING', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
