# Generated by Django 4.2.5 on 2024-06-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0005_orderobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderobject',
            name='delivery_charge',
            field=models.IntegerField(default=100),
        ),
    ]
