# Generated by Django 4.2.5 on 2024-06-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0006_alter_orderobject_delivery_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderobject',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
