# Generated by Django 4.2.5 on 2024-06-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_app', '0007_orderobject_is_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='saved_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20)),
                ('card_date', models.CharField(max_length=5)),
                ('user_name', models.CharField(max_length=30)),
                ('card_provider', models.CharField(max_length=10)),
                ('card_cvv', models.CharField(max_length=3)),
            ],
        ),
    ]
